[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
FirstOrderLp = "29002642-da4a-11e8-3a94-39bc61281718"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
